### ISSUE TITLE
crash on promoting feature from point to line

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#100]
Crashlytics caught this.  Adding to issues list for tracking since this is something I worked on.

When a user would select a point and would promote this to a line, the app would crash. The point feature being referenced by the identify results list would be swapped out to point to a line feature.  In iOS you can't change a list of items while you're stepping through them, which I was doing in my code.  Fix was checked in on 8-24-2015, so it will be part of the 1.2 build.

**Comment by joeschmit** [comment]
Thanks Reed

Sent from my iPhone

On Aug 24, 2015, at 2:59 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Crashlytics caught this. Adding to issues list for tracking since this is something I worked on.

When a user would select a point and would promote this to a line, the app would crash. The point feature being referenced by the identify results list would be swapped out to point to a line feature. In iOS you can't change a list of items while you're stepping through them, which I was doing in my code. Fix was checked in on 8-24-2015, so it will be part of the 1.2 build.

�
