### ISSUE TITLE
RCE Enhancement: TEF Cost Estimates Export

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1026]
One more thing to update in the new RCE down the road...just noticed that when you go to Find TEF Cost Estimates page that it has the same address link as K-Job and when you hit export to excel it titles it as K-job results instead of TEF.

**Comment by jhudsonWA** [comment]
It does, we didn’t want to duplicate them since the forms are 99% the same:

http://hatsprod.wsdot.loc/Maintenance/management/activities/Estimates/FindKJobRecords?loadFromSavedVariables=False&recorddeleted=False&tef=True&kjob=False

But we set a flag at the end for tef=true

However, the export should be labeled TEF

On Jun 21, 2018, at 1:51 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


One more thing to update in the new RCE down the road...just noticed that when you go to Find TEF Cost Estimates page that it has the same address link as K-Job and when you hit export to excel it titles it as K-job results instead of TEF.

**Comment by sheppamwsdot** [comment]
This has been moved to Dev Ops
