### ISSUE TITLE
Budget Tool: Missing Total Plan for Appropriation on Maintenance Budget Report

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1056]
The Total Plan column is blank in the Maintenance Budget Report spreadsheet for the Appropriation tabs. There are some numbers in the Appropriation totals on Control Totals, so there should be some numbers in that column.

**Comment by brianblood** [comment]
This is by design.  The Control Totals page doesn't break things out by month, so these reports have to sum up all of the monthly budget data from each of the regions. 
I just assigned $100 for months 1 - 6 for both NWR and SWR for Appropriation code 030.  If you run the report and select one of those months, you will see the total plan is $1200, and the monthly plan is $200.
If you selected a monthy greater than 6, your monthly plan should have $0, but the total plan will still show $1200.
If you uncheck "Use Monthly Budget" at the two-digit level for a region, the system will fall back to the four-digit level and sum up all of the assigned money for each area on the region.  If any of the four-digit codes are not using the monthly budget, it will fall back to the six-digit level.  
Feel free to call if you have questions, I can imagine this one causing some head-scratching.

**Comment by kechinn** [comment]
Right, makes sense. Thanks for clearing that one up! Learning more and more about how our budget works everyday:)

**Comment by brianblood** [comment]
Same!
