### ISSUE TITLE
Sync isn't assigning Wsdot IDs to map features

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#1065]
The async pattern change with the 100.x SDK is resulting in Wsdot IDs not being assigned to map features in time before the sync with the server starts.

I'm adjusting the PostNewRoadsideFeatureSyncTask so that the nextSyncTask doesn't start until after all the possible code paths finish, including the background thread calls to update the hasPendingWork and WsdotFeatureNumber attributes on map features.

Thanks Oai for noticing this.

**Comment by jhudsonWA** [comment]
Let me know when fix is checked in and I’ll create a new beta today with all the changes/fixes you made this week.

On Jul 19, 2018, at 9:03 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


The async pattern change with the 100.x SDK is resulting in Wsdot IDs not being assigned to map features in time before the sync with the server starts.

I'm adjusting the PostNewRoadsideFeatureSyncTask so that the nextSyncTask doesn't start until after all the possible code paths finish, including the background thread calls to update the hasPendingWork and WsdotFeatureNumber attributes on map features.

Thanks Oai for noticing this.

**Comment by ReedHunter-Wsdot** [comment]
Will do.

There's also a possible crash on [Collect GPS] bug #1018 out there.  Do you want that fixed too first?

**Comment by jhudsonWA** [comment]
If it’s a quick fix once you get to it. If not there is always another beta : )

On Jul 19, 2018, at 9:11 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Will do.

There's also a possible crash on [Collect GPS] bug #1018<https://github.com/WSDOT/HATS/issues/1018> out there. Do you want that fixed too first?

**Comment by ReedHunter-Wsdot** [comment]
fixed
