### ISSUE TITLE
Edit Feature Location Region/Maintenance Area

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1078]
Would like to make these two fields required. Right now it is possible to un-select Region and/or Maintenance Area and sync those changes to web.

**Comment by jhudsonWA** [comment]
Both or just Region? I can make this change for 3.7

On Jul 30, 2018, at 1:40 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Would like to make these two fields required. Right now it is possible to un-select Region and/or Maintenance Area and sync those changes to web.

**Comment by kechinn** [comment]
I would think both should be required, just like on web. Fortunately, it doesn't seem that if you sync it that it does what it did before and make the buttons all disappear on the iPad when there is no region/maintenance area assigned. But maybe something else would trigger it later.

**Comment by jhudsonWA** [comment]
Hmm, I would of thought it would make the buttons go away. :)

I think it doesn’t because the local side still knows about it. The issue with the blank buttons in the past is that the snapshots include features without region but a sync to local db does not (new local database or new features). However if the feature is already on the local side, then updated, it would still be there.

I’ll make both required.

- Josh

On Jul 30, 2018, at 1:56 PM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


I would think both should be required, just like on web. Fortunately, it doesn't seem that if you sync it that it does what it did before and make the buttons all disappear on the iPad when there is no region/maintenance area assigned. But maybe something else would trigger it later.

**Comment by jhudsonWA** [comment]
Fixed in both 3.7 and 4.0 beta. Will be testable in next beta.
