### ISSUE TITLE
MAP Field Survey SR/MP Export

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1079]
The SR/MP is blank when exporting MAP from feature activities report.

**Comment by jhudsonWA** [comment]
Looking into it. Seems like the current feature location was not saved to the record itself as it should have. We can fix this easy enough. Working on it.

**Comment by jhudsonWA** [comment]
So reason this data was not captured is location is turned off for these activities. On feature records it's safe to just leave them on because location is then pulled from the feature location. 

<img width="597" alt="screen shot 2018-08-01 at 9 19 16 am" src="https://user-images.githubusercontent.com/702446/43534416-280c3ee2-956c-11e8-82c1-2a1a1ae0a539.png">

**Comment by jhudsonWA** [comment]
I'll write a process to fix this for this year these settings should be set to true for any activity that is tied to feature inventory. Otherwise location will not be saved.

**Comment by jhudsonWA** [comment]
@kechinn see thread.

**Comment by jhudsonWA** [comment]
Script ran. I've also set those activities to location = true
