### ISSUE TITLE
Aeronautical Chart Map Overlay iOS and HATS Web.

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1092]
Can we please look into adding an Aeronautical Chart Map for sUAS operations? It would be really beneficial for planning sUAS missions. in order to know what airspace we are in using the combination of highway mile markers and the aeronautical chart. This would help us plan flights in advance. I've eyeballed google earth, HATS, and skyvector.com in advance thinking my flight plan was ok, and actually when on site was notified by the DJI Go 4 app that I was in controlled airspace and unable to fly the mission.  

Kind of like Orthophotos overlay?  Cut up by region?

ESRI Sectional Charts!!!! https://www.arcgis.com/home/item.html?id=d91ee8e3fafe4140bfda73fe577fbcdd

Or Chartbundle? https://www.arcgis.com/home/item.html?id=597896e2ea9e4c4abd5951b155bfb61f

Or Open API MAP!!!!!!? Polygons! HERE ---->  https://www.openaip.net/
 http://maps.openaip.net/?destination=http://www.openaip.net .

**Comment by jhudsonWA** [comment]
One of team members will reach out to you soon. Thank you for your feedback. 😁

Sent from my iPhone

On Aug 16, 2018, at 10:25 AM, Pete <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we please look into adding an Aeronautical Chart Map for sUAS operations? It would be really beneficial for planning a sUAS missions. in order to know what airspace we are in using the combination of highway mile markers and the aeronautical chart. This would help us plan flights in advance. I've eyeballed google earth, HATS, and skyvector.com<http://skyvector.com> in advance thinking my flight plan was ok, and actually when on site was notified by the DJI Go 4 app that I was in controlled airspace and unable to fly the mission.

Kind of like Orthophotos overlay? Cut up by region?

Or Open API MAP!!!!!!? Polygons! HERE ----> http://maps.openaip.net/?destination=http://www.openaip.net .

https://www.iflightplanner.com/AviationCharts/

Or is this an idea for a separate app?

https://skyvector.com/

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Can we add the ESRI charts as a layer? See above for link. And does it have to be a online layer?

**Comment by ReedHunter-Wsdot** [comment]
I have downloaded some data in the hopes of converting this into something we can use.  No luck yet.  Worst case is this will be an online basemap.  Best case is I'll be able to add some aviation layers to the offline basemap.

**Comment by ReedHunter-Wsdot** [comment]
The data I acquired was just airport points, not the airspace restriction data shown in the national airspace maps.  We have some obstacle interception surfaces around airports that we're using within another application.  I'm taking a look at whether we can use that offline since this data was vetted by Carter Timmerman over in aviation.

**Comment by ReedHunter-Wsdot** [comment]
I've gotten my hands on restricted airspace polygons, and I can buffer 5 mile polygons around airport centerpoints.  I will add those to the offline basemap, but I'll keep them turned off by default since I haven't heard of that most crews need this. We already have national park polygons, which are relevant since those are also restricted airspaces.  

There is an app from the FAA with more authoritative data called B4UFly.  It doesn't work offline.

There is another app called Drone Buddy that can cache a more robust set of no fly zone data offline than I have been able to find such as prisons, schools, power plants, hospitals, etc.  It also captures weather and wild fire information (another UAS restricted area) when online.  The map flickers a lot when offline, and it only shows what it interactively cached when it was online, but it works and is more responsive than B4UFly.
