### ISSUE TITLE
For non admins

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#1109]
while searching inventory by bridge number, it requires them to select a region and maintenance area. Can you please make it so it doesn't require those inputs?

**Comment by brianblood** [comment]
Hey Oai - how desperate are the users for this?  Forcing the users to either provide a feature number or limit to a specific region or SR is there to prevent them from hammering the server with queries that return huge datasets.
Searching by bridge number would fit this requirement on paper, but since we would be searching against a dynamically generated attribute field there is no way to know this ahead of time unless we add a flag to the attributes table / Feature Attributes admin page explicitly saying that this is an attribute that can be used in a statewide search.

**Comment by jhudsonWA** [comment]
I like that solution Brian. Make it so. This won't be used much, but something like bridge number is a special case where it is like the Feature Number where it is unique across all bridges. We don't even need to make editing this flag an admin screen function. It's something we could toggle behind the scenes in the few cases where its needed.

**Comment by brianblood** [comment]
This is now in prod.
