### ISSUE TITLE
HATS 4.0 B11: Double Tap Zooming

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1173]
If you double tap and hold anywhere on map and slide your finger up or down it will zoom in and out of map. Since there are lots of double tap users, is it possible to get rid of this feature?

**Comment by ReedHunter-Wsdot** [comment]
Esri exposes no option to turn off double-tap zoom support.  I can only disable zooming in/out in general in the map interaction options, not how that is controlled.

**Comment by ReedHunter-Wsdot** [comment]
Just to be sure about this, can you give me a call Keisha?  I'm wary because I just looked at production 3.8 HATS vs 4.0 beta, and I'm not seeing any difference between the old map behavior for douple taps and pinch zooms we've had since 2015 vs what we have now.  I can make an enhancement request to Esri, but I want to know what you're thinking before leaving this closed or making that request.

**Comment by ReedHunter-Wsdot** [comment]
Thanks @kechinn, now I see the difference.  In the new environment you don't lift your finger after the double tap, then you slide vertically to cause a zoom in/out.  This looks like a new map interaction feature of the 100.x sdk.  I don't have the ability to revert this back to the 10.2.5 Sdk's interaction style.

**Comment by kechinn** [comment]
@PeterBurkhard New training tip :)
