### ISSUE TITLE
HATS 4.0 B11: Collect GPS Bug When Updating Existing Point Features

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1174]
Collect GPS not working with point features if you delete vertex either by double tap and remove/clear option, or by standard delete vertex button. Works after undo or restart though. Not seeing issue with lines or polygons. Issue only pops up when updating an existing feature. No issue collecting gps after deleting with new features.

**Comment by ReedHunter-Wsdot** [comment]
I'm not sure of the steps to trigger this, but I found a bug that closely matched this.  The steps to reproduce were to ...
1. identify a feature
2. edit that feature so that it's changed in some way.
3. identify another feature
4. attempt to edit that feature

result was that the geometry feedback woudn't show up, and my taps on the screen would no longer update the sketch.  This was a different bug than what I fixed for #1176 .

Please test again @kechinn and let me know if this still shows up.  If it does, please jot down the steps to reproduce this so I can track it down and fix it.

Thanks

**Comment by ReedHunter-Wsdot** [comment]
I failed to mention yesterday that I checked in a fix for the bug that was triggered with the above steps.  That fix is part of today's beta.  If you don't see the original bug you filed, then let's close this one.

Thanks
