### ISSUE TITLE
HATS 4.0 Beta: Sync Text Enhancement

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1175]
In current prod version (not seeing in Beta), when you add a new feature and sync, in the text you can see what WSDOT Feature ID # the new feature is assigned to. I have used this in the past to locate features on iOS or web right afterwards, instead of having to go search for the feature I created and identifying. Especially helpful if the new feature was small and hidden within a bunch of other features, in a place not near your current GPS location. Is it possible to bring this back?

![1a057775-71ef-445d-a733-5865a8b97559](https://user-images.githubusercontent.com/16247034/47858759-fab24a00-dda9-11e8-9f8c-9abb57404a42.jpeg)

**Comment by jhudsonWA** [comment]
I’ll check this one. I’m not sure why it would of been dropped in 4.0

On Nov 1, 2018, at 8:00 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


In current prod version (not seeing in Beta), when you add a new feature and sync, in the text you can see what WSDOT Feature ID # the new feature is assigned to. I have used this in the past to locate features on iOS or web right afterwards, instead of having to go search for the feature I created and identifying. Especially helpful if the new feature was small and hidden within a bunch of other features, in a place not near your current GPS location. Is it possible to bring this back?

[1a057775-71ef-445d-a733-5865a8b97559]<https://user-images.githubusercontent.com/16247034/47858759-fab24a00-dda9-11e8-9f8c-9abb57404a42.jpeg>

**Comment by jhudsonWA** [comment]
Fixed. Will be in next Beta.
