### ISSUE TITLE
Budget Tool: 6B4 Dollar Amount Issue

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#1178]
Looking at Cognos reports, 6B4 is showing $190,000 more than what the HATS Budget Tool Program M Budget Report is showing in the Total Planned for 6B4. 

Looking at the SWR tab Org 4420 Sub-Program M2, there is a dollar allotment of $190,000. Not sure why it is not adding to the Total Planned in report. Ideas?

HATS Report:
![image](https://user-images.githubusercontent.com/16247034/47885554-e5add900-ddf2-11e8-8e79-d5983d392b0b.png)

COGNOS Report:
![image](https://user-images.githubusercontent.com/16247034/47885628-3b828100-ddf3-11e8-81c6-9c5bf6b82be2.png)

**Comment by brianblood** [comment]
Hi Keisha,
Took me some time to figure out what I was looking at, but I think I see what's happening.  

The reports are only summing up data from forms that have "Use monthly budget" checked.  For those that do not use monthly a budget, like 4420, we don't know how that 190k is allocated amongst the different months/work op classes, so we fail downwards to the child orgs until we hit a monthly budget.  
In the report you attached, the two digit code 44 does not use a monthly budget, so it looks at everybody at the four digit level.  4400 also does not use a detailed budget, so it then looks at it's children.  There is only one six digit child, 442002, and all of it's values are zero, so that $190k should not appear in any report totals that are breaking things down by month, Workop Class or SubSubObject.

If you total up the 6B4 entries across all of the of the four-digit orgs (all of the rest use the monthly budget) in SWR, you get $95,905.

I'm not sure what you've got COGNOS doing, but it looks like, if 'use monthly budget' is un-checked, it is just grabbing the value for dollar allotment at adding it in to the last entry in the list.  

Feel free to give me a call if this isn't making sense.
