### ISSUE TITLE
HATS Check For Updates

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1244]
Can we make HATS automatically check for updates? Joe bought this up yesterday, great idea. Can we have HATS ping Meraki or the App store? User gets a notification upon launch that there is an update in case the Meraki push fails like it does often for various reasons.

**Comment by jhudsonWA** [comment]
Denied. You only get one request a day.

**Comment by joeschmit** [comment]
Yea @jhudsonWA why not a button that users can smash to say "Check for updates" boom! Then maybe we won't get random DB uploads ha.

**Comment by joeschmit** [comment]
@PeterBurkhard must be Git'ing bored

**Comment by jhudsonWA** [comment]
Do you want a button or just part of sync? On sync it could throw up a message at the end if they aren't using the latest.

**Comment by joeschmit** [comment]
I'm fine with on sync.

**Comment by jhudsonWA** [comment]
Ok, I'll make it so.

**Comment by jhudsonWA** [comment]
So sync vs button:

Right now I coded it so it will check the version and alert the user if there is a new version and what it is. 

What should the message say? And right now it pops up after every sync if there is a newer version. 

If we did the button users may never hit it, but if they did it will tell them a new version exists, and what would that message say?

One thing to note when you think about this. If we do it on sync this will trigger the first time a user does a sync after a new version is out (after 4.1 of course). Even if it is minutes after deployment because the server will have a new version. The MDM will not have had time to push it out to all devices but they will still get the message. 

So sync or button?        Or Sync and button?   Messages and timing thoughts?

**Comment by jhudsonWA** [comment]
I got it at least logging the result of the check on sync now.

Update Available:

![simulator screen shot - ipad pro 9 7-inch - 2019-01-16 at 13 48 45](https://user-images.githubusercontent.com/702446/51280792-737e7680-1995-11e9-8e48-476dad8607fd.png)

Up to date:
![simulator screen shot - ipad pro 9 7-inch - 2019-01-16 at 13 49 53](https://user-images.githubusercontent.com/702446/51280851-9c067080-1995-11e9-98d9-dbb8d90689e1.png)

Pre-release software:

![simulator screen shot - ipad pro 9 7-inch - 2019-01-16 at 13 51 04](https://user-images.githubusercontent.com/702446/51280914-c6f0c480-1995-11e9-9ece-6d4f2378f041.png)

**Comment by jhudsonWA** [comment]
And this is automatic. We don't have to remember to change a value on deployment of a new value. The process actually reads the deployment manifest on our servers that the mdm uses and gets automatically created on deployment.

**Comment by jhudsonWA** [comment]
Ok, called Joe! Button + sync message is what we will go with.

**Comment by jhudsonWA** [comment]
Found out a way to make button kick of a download of the latest version. Boom! Will be in next beta.
