### ISSUE TITLE
Collect gps undo retry GPS no go,  unless you move. Similar to #1195

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#1274]
"So the issue is the last gps spot is cleared from the map, but not from internal data structures. I know that’s the issue, but I’m afraid if I made changes I would break something else and Reed isn’t in. You shouldn’t have to move far, even a foot or two will do it. I’ll check with him tomorrow, but this may have to be 4.5. I don’t believe it’s a change, and previous behavior would of been the same." - Josh
![gpsundo](https://user-images.githubusercontent.com/15268732/52303129-02066800-2944-11e9-9ee2-d1c1aaa1eb75.gif)

**Comment by jhudsonWA** [comment]
@ReedHunter-Wsdot Issue is lastGPSPoint is not touched on undo/redo. Thoughts? Should we bump to 4.5?

**Comment by ReedHunter-Wsdot** [comment]
I was able to recreate this scenario, so let's not bump this.  I should be able to fix this shortly.

**Comment by ReedHunter-Wsdot** [comment]
Fixed.  

Back when I fixed Git 1195 I did all my testing and development with editing an existing feature, and then ported the changes over to the add new feature tool.  I added the new code, but missed that I also needed to cut away a small section from the Add features tool.  This old code is now excised and the problem is fixed.
