### ISSUE TITLE
Crashing Map Bug: Features not being removed after Admin toggle Active/Published = False ca

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#1331]
When changing Admin > Map Feature Type > Active & Published to False, sync feature drops from TOC but stays on MAP, on Identify crash

**Comment by joeschmit** [comment]
Ref FeatureTypeID = 147 MAP bridge sites

**Comment by ReedHunter-Wsdot** [comment]
I updated HATS to look for this setting before loading any layer into the map.  This won't help until the change is deployed.

As a workaround for our current HATS release, I saved a copy of the bridge points and then deleted them from the map on the server.  When the crews sync, the deletes will propagate down to their local iPads.  The layer will still be quietly loading in their map, but they'll never see it because the layer will be empty.
