### ISSUE TITLE
True-up Stormwater BMPs

### ISSUE THREAD

**Issue by suttert** [WSDOT/HATS#1354]
We need a true up on the following stormwater BMPs:

32 | 43 | 52 | 57 | 75 | 83 | 89
33 | 44 | 53 | 58 | 76 | 85 | 97
40 | 45 | 54 | 59 | 80 | 86 | 104
41 | 46 | 55 | 60 | 81 | 87 | 118
42 | 47 | 56 | 62 | 82 | 88 | 119

**Comment by ReedHunter-Wsdot** [comment]
Some of these feature types have nothing in HighwayActivitiesTracking.  Truing them up will mean deleting everything from the map.  I'm wary of possible bad input in this situation. 

81 - Infiltration Trench, currently at 1 point and 133 lines.
83 - Web Biofiltration Swale, current at 30 lines in the map
85 - Engineered Dispersion, currently at 22 line features
86 - Media Filter Drain, currently at 4 point features and 509 line features
87 - Natural Dispersion, currently at 131 line features
88 - Vegetated Filter Strip, currently at 251 line features
97 - Combined Treatment Wet/Detention Pond, currently with 45 point features
118- CAVFS, currently at 26 line features

Josh will take a look at the snapshot tables and confirm they're up to date.

**Comment by ReedHunter-Wsdot** [comment]
@suttert ,  119 - CABS isn't published, so there's no data to true up.  Should this be published?

**Comment by suttert** [comment]
Yes, I'm not sure any are active yet but we have some under construction

**Comment by ReedHunter-Wsdot** [comment]
Another issue I spotted was that Linear Sand Filter (type 82) and Continuous Inflow Bio Swale (type 80) are in the map, but only as points.  They're listed in the HighwayActivities database as being lines, so I think this is an old mistake of mine to have only ever published these as points.

I plan on adding these as lines to the 4.4 maps in the coming weeks.  This will break sync compatibility, so expect to have to redownload a new features map when I make that update.  There are 0 features anywhere btw for those two types, so that's two where there is nothing to true up.

**Comment by ReedHunter-Wsdot** [comment]
This is completed.
