### ISSUE TITLE
Drop/Recreate map UI on basemap redownload

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [WSDOT/HATS#269]
When someone redownloads the basemap, new layers don't show up.  Map UI needs to be dropped/reloaded to reflect changes in the basemap after a redownload.

**Comment by ReedHunter-Wsdot** [comment]
Josh, fyi I just tested this and the code change you slipped in a few weeks ago didn't correct this.  Since this isn't in Joe's list for 2.0, I'm bumping pursuit of this feature to the next release.

**Comment by jhudsonWA** [comment]
Well that's good, because I didn't change anything :) I just noticed the map did get removed from memory when that workflow was followed.

Sent from my iPhone

On May 27, 2016, at 3:33 PM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:

Josh, fyi I just tested this and the code change you slipped in a few weeks ago didn't correct this. Since this isn't in Joe's list for 2.0, I'm bumping pursuit of this feature to the next release.

�

**Comment by ReedHunter-Wsdot** [comment]
This looks to be an Esri SDK issue.  Once you open a datasource the SDK will cache it under the covers.  Replace the datasource with a new file and the SDK will still give you the old one.  The only way to clear this cache is to restart the app.  I'll file a bug with Esri.
