### ISSUE TITLE
Change Feature Type Name: Noxious Weed Control 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#328]
Hey Josh,

Since we're adding another general weed point feature, #323, can we rename the exisiting Noxious Weed Control feature to "Noxious Weed Control Priority"?

**Comment by jhudsonWA** [comment]
Yep

Sent from my iPhone

On Feb 22, 2016, at 9:09 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey Josh,

Since we're adding another general weed point feature, #323https://github.com/WSDOT/HATS/issues/323, can we rename the exisiting Noxious Weed Control feature to "Noxious Weed Control Priority"?

�

**Comment by jhudsonWA** [comment]
You should be able to do this in QA now yourself. Joe can show you how.

**Comment by jhudsonWA** [comment]
Name updated in QA/Prod
