### ISSUE TITLE
[HATS iOS] Symbology Change for Features that have been inspected/maintained within a timeframe

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#42]
On the map view provide for a way to change symbology (red dot to green dot) once an inspection has been completed.  We are seeing users duplicating inspections because it is not simple enough to show where the last crew left off with inspections etc.  This is pretty specific to catch basins/culverts where we have annual requirements for inspections and maintenance.

**Comment by ReedHunter-Wsdot** [comment]
This will be implemented like notes - with a separate layer for displaying dots, another for lines, another for polygons symbolized based on how long since the last inspection.  This will require code updates to the identify command to make it ignore such layers, and some back end functions to update inspection date syncs across devices.  
Timeline to implement will make this post 1.5.

**Comment by jhudsonWA** [comment]
Replace with #775
