### ISSUE TITLE
Add "Source System" data to Identify Popover

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#456]
Add "Source System" data to Identify Popover', this should include the date as well.

Business need, to understand which system added the feature and when it was added, especially useful in the field relating to the SWID/HATS ETL...

**Comment by jhudsonWA** [comment]
Uploaded to /beta as 2.0 B4. Since this data needs to be added to the local database for every feature in the state, users will be asked to download a new local database after their first successful sync.
![screen shot 2016-05-26 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/702446/15593900/46f0dc26-2365-11e6-922c-97ec3edafdf4.png)
