### ISSUE TITLE
Culvert attribute change

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#465]
Culvert attribute change:
1. Remove - "Fish Barrier" and replace with "Fish Barrier Status (If uncertain, do not make a selection)" add the following as a drop down selection "On statewide fish barrier list" and "On culvert lawsuit injunction barrier list" - NOT REQUIRED
2. Add Plain Steel, Add word Corrugated to Polyethylene PE and migrate existing culvert attributes
3. Add Other to Orientation and migrate any NA values to Other
4. Change CMS and MMS to CMs and MMs

**Comment by jhudsonWA** [comment]
Working on now.

On Jun 6, 2016, at 11:39 AM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Culvert attribute change:
1.  Remove - "Fish Barrier" and replace with "Fish Barrier Status (If uncertain, do not make a selection)" add the following as a drop down selection "On statewide fish barrier list" and "On culvert lawsuit injunction barrier list" - NOT REQUIRED
2.  Add Plain Steel, Add word Corrugated to Polyethylene PE and migrate existing culvert attributes
3.  Add Other to Orientation and migrate any NA values to Other
4.  Change CMS and MMS to CMs and MMs

**Comment by jhudsonWA** [comment]
Ran in QA: May want to grab the latest beta version if you want to test on the iPad. If not, just do a sync with whatever beta you have.

On Jun 6, 2016, at 11:39 AM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Culvert attribute change:
1.  Remove - "Fish Barrier" and replace with "Fish Barrier Status (If uncertain, do not make a selection)" add the following as a drop down selection "On statewide fish barrier list" and "On culvert lawsuit injunction barrier list" - NOT REQUIRED
2.  Add Plain Steel, Add word Corrugated to Polyethylene PE and migrate existing culvert attributes
3.  Add Other to Orientation and migrate any NA values to Other
4.  Change CMS and MMS to CMs and MMs

**Comment by tangoai** [comment]
Josh, Gregor really wants it to say "Fish Barrier Status (If uncertain, do not make a selection)" Will this be an issue on your end?

**Comment by jhudsonWA** [comment]
Oh yes, that is not possible. Much too long.
On Jun 6, 2016, at 3:11 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Josh, Gregor really wants it to say "Fish Barrier Status (If uncertain, do not make a selection)" Will this be an issue on your end?

**Comment by jhudsonWA** [comment]
The max length is 50 characters.

On Jun 6, 2016, at 3:11 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Josh, Gregor really wants it to say "Fish Barrier Status (If uncertain, do not make a selection)" Will this be an issue on your end?

**Comment by tangoai** [comment]
How about "Fish Barrier Status (If uncertain do not select)"

**Comment by jhudsonWA** [comment]
That fits. Sync away.
On Jun 6, 2016, at 3:31 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

How about "Fish Barrier Status (If uncertain do not select)"

**Comment by joeschmit** [comment]
If they don't know why would they answer it?  Hence "required = false"...

I'm kind of annoyed with the ongoing "this isn't the choice you aren't choosing..." Stuff...smh

Sent from my iPhone

On Jun 6, 2016, at 3:34 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

That fits. Sync away.
On Jun 6, 2016, at 3:31 PM, tangoai <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:

How about "Fish Barrier Status (If uncertain do not select)"

�
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHubhttps://github.com/WSDOT/HATS/issues/465#issuecomment-224108938, or mute the threadhttps://github.com/notifications/unsubscribe/AAq37nwCSoqL2mmrLBSGTJxu7mHWDIX_ks5qJJ-3gaJpZM4IvMCs.

�

**Comment by tangoai** [comment]
Josh "Plain Steel" was left off the material type. Sorry, hopefully this will be the last!

**Comment by jhudsonWA** [comment]
¯_(ツ)_/¯

Sent from my iPhone

On Jun 6, 2016, at 3:59 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:

If they don't know why would they answer it? Hence "required = false"...

I'm kind of annoyed with the ongoing "this isn't the choice you aren't choosing..." Stuff...smh

Sent from my iPhone

On Jun 6, 2016, at 3:34 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:

That fits. Sync away.
On Jun 6, 2016, at 3:31 PM, tangoai <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.commailto:notifications@github.com> wrote:

How about "Fish Barrier Status (If uncertain do not select)"

�
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHubhttps://github.com/WSDOT/HATS/issues/465#issuecomment-224108938, or mute the threadhttps://github.com/notifications/unsubscribe/AAq37nwCSoqL2mmrLBSGTJxu7mHWDIX_ks5qJJ-3gaJpZM4IvMCs.

�

**Comment by jhudsonWA** [comment]
Done. Please sync.

On Jun 6, 2016, at 4:10 PM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

Josh "Plain Steel" was left off the material type. Sorry, hopefully this will be the last!

**Comment by jhudsonWA** [comment]
Please let me know if this is how he wants it and I'll run the script in production.

**Comment by tangoai** [comment]
He says to keep it in beta for now.

**Comment by jhudsonWA** [comment]
Ok. For how long? These ASAP attribute requests generally spend a day in BETA then are moved out so they are off my plate.

Sent from my iPhone

On Jun 7, 2016, at 7:43 AM, tangoai <notifications@github.com<mailto:notifications@github.com>> wrote:

He says to keep it in beta for now.

�

**Comment by jhudsonWA** [comment]
Production updated. Fish Barrier Status is currently disabled and can be turned on when you guys are ready.
