### ISSUE TITLE
Hide SWID and RFIP pipes per Trett's request

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#496]
Please hide SWID and RFIP pipes per conversion below.  

No, we separated culverts out to their own feature type since the beginning. Oai, can you create a HATS issue and we can make this happen for 2.0 (around July 11th)

On Jun 20, 2016, at 3:19 PM, Sutter, Trett SutterT@wsdot.wa.gov wrote:

That’s part of it but he collects a lot of linear underground pipe features that we would prefer maintenance not guessing at. I would only like them to collect the outfall of a pipe feature as a singular point feature.

I think we should hide SWID pipes and maybe RFIP if they also collected pipes.

Will this mess with our existing linear culvert inventory?

From: Hudson, Joshua 
Sent: Monday, June 20, 2016 3:02 PM
To: Sutter, Trett
Cc: Schmit, Joe; Tang, Oai
Subject: Re: Pipe Features

We can do this. Is this because Cory says culverts are pipes so more pipes are showing up on the iPad than should?

What should be the plan, just hide all SWID pipes?

**Comment by jhudsonWA** [comment]
This will affect around 6000 pipes. We will make this change with 2.0

**Comment by jhudsonWA** [comment]
select \* from RoadsideFeature where RoadsideFeatureTypeId = 72 and (DatasourceId = 5 or DataSourceId = 1)

**Comment by jhudsonWA** [comment]
So I did verify that pipes are already on the non ETL type list so new ones shouldn't copy. But that probably doesn't matter for updates. The original run of the ETL must of found the RFIP pipes and made them SWID pipes.

I did verify no records have been created from SWID pipes. Our pipe local feature type is actually tied to pipe ends in the roadside feature table. 

I could hide all 6000+ pipes, or just delete them from our database (instead of hide, since I'm afraid that if hidden a future update by Cory could cause them to unhide) since they are not tied to anything and are stored in the Stormwater DB as the authoritative thoughts. @joeschmit @suttert thoughts?

**Comment by jhudsonWA** [comment]
Oops :) So with further research we have two things. 

There are 6000+ pipes from SWID and RFIP (typeid 72) in our database but they are not used anywhere. The map and the web don't see them as they only look at type id 24 (RoadsideFeatureType : Pipe Ends)

What we call pipes on the web and iPad in our database are actually pipe ends in the roadside feature type database (type id 24). These are currently shown on the web and iPad. Out of 2393 features all of them are either RFIP or SWID. It looks like around 2260 of these are non retired. So I'm not sure you really want to hide all off them or you will be reseting your inventory to 0. Feature 847255 is an example of this. 

I'm thinking before we do anything a phone meeting would be useful. @joeschmit @suttert

**Comment by jhudsonWA** [comment]
Ok, had a phone meeting with @suttert this morning. Per his request I have hidden all RFIP and SWID pipe ends (what show up as pipes in the HATS application). This leaves around 800 pipe ends (pipes) remaining in HATS.

I had the wrong window open when I ran the script so this is already done in Prod and QA. The prod and BETA iPad maps will still show the features as we don't want to reload the beta one and the prod one will be fixed on monday when we ship 2.0
