### ISSUE TITLE
MAP survey 2016 sites records should close out related pending activities (like cleaning)

### ISSUE THREAD

**Issue by tangoai** [WSDOT/HATS#498]
which includes Field Survey: Roadside/Drainage, Field Survey: Roadway/Traffic, and Bridge MAP survey. Similar to what you did for the Cleaning activity form for catchbasins.

**Comment by jhudsonWA** [comment]
Changes now in place on server. 

"Ok, I added the code to close out any pending activities with those 3 activities to the server. Like cleaning on a feature it will close out all cleaning pending activities. But also like cleaning you don’t get the nice link between the *\* FOR HQ *\* feature pending activity and the record they created. All it does is close the pending activities that match that activity. Which shouldn’t matter since the *\* FOR HQ *\* activities are not real activities anyway. Long story short, you will now get pending activities created using *\* FOR HQ *\* and if they close one out in the field by just creating a record each night it will clean up the pink outline. "
