### ISSUE TITLE
Map: Allow Adding/Editing Polygon Features

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#555]
This mostly is in my side. Right now I don't have to code to parse the ESRI JSON for polygons.

**Comment by kechinn** [comment]
@jhudsonWA Do you think this is doable for iOS 3.0? I've been getting a few more of these requests for editing of Roadside polygon features since the creation of the Pesticide form. If not, I would just continue to draw them in another program and send to you and Reed for updating. But it would be pretty neat to digitize polygons in the field.

**Comment by jhudsonWA** [comment]
I would think so for 3.0

Sent from my iPhone

On May 3, 2017, at 8:44 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhudsonWA<https://github.com/jhudsonWA> Do you think this is doable for iOS 3.0? I've been getting a few more of these requests for editing of Roadside polygon features since the creation of the Pesticide form. If not, I would just continue to draw them in another program and send to you and Reed for updating. But it would be pretty neat to digitize polygons in the field.

**Comment by jhudsonWA** [comment]
Simple polygon editing enabled 3.0b10

**Comment by joeschmit** [comment]
Boom!

- Schmit

On Sep 7, 2017, at 6:19 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


Simple polygon editing enabled 3.0b10
