### ISSUE TITLE
Web Map: Add AVL Truck Layer

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#564]
Show current truck locations, same clickable popups as AVL

**Comment by ReedHunter-Wsdot** [comment]
Status updates:  Tried 1st version of this using the 4.1 (latest) ArcGIS JavaScript API.  It was too new though, only supporting static data like cities or parcels, stuff that unlike trucks doesn't move around.  I scrapped that and went with the 3.18 API.  That works, but the out of box refresh is slow for the several truck map layers I have.  It takes between 20 and 30 seconds to refresh when I pan/zoom.  A copy of this is for now available at http://webteamtest/Maintenance/Management/Activities.

**Comment by ReedHunter-Wsdot** [comment]
I have a truck query UI built into this code that will let you see basic truck info if you hover the mouse over the truck.  This UI is made to look similar to what folks will be used to with the Operations map UI.

**Comment by ReedHunter-Wsdot** [comment]
I have that pan/zoom wait time cut down to about 4 seconds by using client snapshot map layers.  Those however are static, so I'm in the process of writing optimized truck layer refresh code.  Once that's ready and tested, Josh will merge the Map code into the Master branch web site and deploy to the test server for Joe and his team to test.  That should be available for Josh by the end of the week of Nov 28 -> Dec 2.

**Comment by ReedHunter-Wsdot** [comment]
Have implemented a query to split AVL truck data into the categories:
0 - IRT Truck
1 - sweeper truck, broom not engaged
2 - sweeper truck, broom engaged
3 - no solid,  no liquid, no plow
4 - no solid,  no liquid,    Plow
5 - no solid,     liquid, no plow
6 - no solid,     liquid,    plow
7 -    solid1, no liquid, no plow, no prewet
8 -    solid1, no liquid, no plow, 	  prewet
9 -    solid1, no liquid,    plow, no prewet
10-    solid1, no liquid,    plow,    prewet
11 -   solid1,    liquid, no plow, no prewet
12 -   solid1,    liquid, no plow,    prewet
13 -   solid1,    liquid,    plow, no prewet
14 -   solid1,    liquid,    plow,    prewet
15 -   solid2, no liquid, no plow, no prewet
16 -   solid2, no liquid, no plow,    prewet
17 -   solid2, no liquid,    plow, no prewet
18 -   solid2, no liquid,    plow,    prewet
19 -   solid2,    liquid, no plow, no prewet
20 -   solid2,    liquid, no plow,    prewet
21 -   solid2,    liquid,    plow, no prewet
22 -   solid2,    liquid,    plow,    prewet

Preliminary graphics for these groups are done, and a test map service is running with this at http://hqolymgis99t.wsdot.loc:6080/arcgis/rest/services/Hats/HATS_Avl_20161221/MapServer
A stock viewer for this is available at http://hqolymgis99t.wsdot.loc:6080/arcgis/rest/services/Hats/HATS_Avl_20161221/MapServer?f=jsapi.  It loads the data differently than HATS-Web, so it will be less responsive.
Since the truck symbols are now custom, I have some more steps to get this loaded into HATS-Web for testing.  


Group 1 solids show with a dark blue color, group2 solids dark green.  The dark blue or green solid color has a reddish orange inside if it's not being prewet.  Light blue means liquid is being applied.

**Comment by ReedHunter-Wsdot** [comment]
http://webteamtest/Maintenance/Management/Activities is now updated with the 23 truck types and icons.  Please take a look.

**Comment by ReedHunter-Wsdot** [comment]
Clickable popups for Avl features done and checked in to Origin/Map branch.
