### ISSUE TITLE
HATS RCE Printing is generating a blank first page for some records

### ISSUE THREAD

**Issue by brianblood** [WSDOT/HATS#647]
Everything is printing properly, it just has an annoying blank first page.  Example record:  K2B053.

**Comment by jhudsonWA** [comment]
My guess is due to 2016 SSRS upgrade. I'll take a look after thanksgiving.

Sent from my iPhone

On Nov 18, 2016, at 1:13 PM, brianblood <notifications@github.com<mailto:notifications@github.com>> wrote:

Everything is printing properly, it just has an annoying blank first page. Example record: K2B053.

�

**Comment by jhudsonWA** [comment]
Fixed for both KJob and General Estimates
