### ISSUE TITLE
Sort LogNote in Application Log 

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#703]
@jhudsonWA  I have a need to separate the information under LogNote in the ApplicationLog into separate columns for QA/QC reporting purposes in the near future. Would make life much easier than writing Substring and CharIndex in my queries. At some point when you're not so busy, can we sit down and chat about this? -Keisha

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Also this one since you are working on Application Log now. What she is looking is this: the log note column currently has a ton of information rolled into it for the iOS API log type. We broke some of these out in the past (device name, model) but there are other parts of the log note that didn't' get pulled out (Action and possibly record id if the type is add record). This makes it harder for @kechinn to query this data as she has to write substring queries to pull this information into columns. Can you work with modelers to pull these out of log note? I believe we went with the naming MobileAppicationX for field names for some of the other columns in ApplicaitonLog that deal with mobile devices.. So please update the logging parts of HATS to populate these columns if coming from the iOS api (look in api controllers) and write a query that pulls and populates this info for past log messages. Thanks.

**Comment by lundyc-wsdot** [comment]
OK


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
@kechinn Can you tell us what columns we should be pulling out of the log note? A ton of them are already separated out.

**Comment by kechinn** [comment]
@jhudsonWA Is it possible to pull out Feature (WSDOT ID), Feature Type, and Activity from LogNote? 
I realize you can find some of this info from the Event Log and other tables through joins, but it simplifies things when querying certain features and activities. Especially since what we have named activities in HATS web/iOS do not always match the ActivityDefinition column Activity Title in CA (e.g. 'Inspection' vs. '1331 - Routine Inspection').

**Comment by jhudsonWA** [comment]
Will revisit this for next web release

**Comment by jhudsonWA** [comment]
@lundyc-wsdot We never got back to this one, for your list. Here is what we need to pull out

"@jhudsonWA Is it possible to pull out Feature (WSDOT ID), Feature Type, and Activity from LogNote?
I realize you can find some of this info from the Event Log and other tables through joins, but it simplifies things when querying certain features and activities. Especially since what we have named activities in HATS web/iOS do not always match the ActivityDefinition column Activity Title in CA (e.g. 'Inspection' vs. '1331 - Routine Inspection')."

**Comment by jhudsonWA** [comment]
Done, in qa, testing now will be in prod early next week

**Comment by jhudsonWA** [comment]
This is in production now. We added two columns RoadsideFeatureId since you can get ASSEtReferenceNumber from that  and Feature Type. ActivityId is also a column now.
