### ISSUE TITLE
Show Fuel as Attribute for Fuel Stations Basemap Layer

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#721]
In HATS iOS, show the Fuel attribute (G, B, D, etc.) from the Fuel Stations basemap layer on identify tap.

**Comment by jhudsonWA** [comment]
@kechinn is this in the new basemap?

**Comment by kechinn** [comment]
@jhudsonWA No, the fuel stations layer has been in the basemap for awhile. Oai and I just hoped to add the field named 'Fuel' as an attribute that would show when you identify those basemap features. Currently, it just shows the 'Name' field.

**Comment by ReedHunter-Wsdot** [comment]
@kechinn, do you think it would be acceptable to crews if we put "Fuel: " + [Fuel] after the name?  
examples: 
Bellevue WSP, Fuel: G
Connel, Fuel: D

We could have this supported this afternoon if we take that route.

**Comment by kechinn** [comment]
@ReedHunter-Wsdot Works for me, that makes more sense.

**Comment by ReedHunter-Wsdot** [comment]
Name field for the fuel stations in the basemap was extended, and the fuel type was appended in that field.  I think I should change the order to have, name + fuel type + " fuel" in the field.  The type of fuel is being cut off in the UI for the longer named stations.  Just north of Spokane the identify results for the station are showing "Spokane (Wandermere), Fuel: ".  If I swap the order the fuel types won't be cut off.

**Comment by jhudsonWA** [comment]
So there are ways to have have the label shrink a bit to fit longer text. I can fix it that way instead of changing the data.

On Jun 8, 2017, at 10:27 AM, Reed Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Name field for the fuel stations in the basemap was extended, and the fuel type was appended in that field. I think I should change the order to have, name + fuel type + " fuel" in the field. The type of fuel is being cut off in the UI for the longer named stations. Just north of Spokane the identify results for the station are showing "Spokane (Wandermere), Fuel: ". If I swap the order the fuel types won't be cut off.

**Comment by ReedHunter-Wsdot** [comment]
@jhudsonWA autoshrink option takes care of the text getting cut off.  The basemap will now work as is.

**Comment by jhudsonWA** [comment]
Fixed using the built in sdk. 
![simulator screen shot jun 8 2017 10 33 39 am](https://user-images.githubusercontent.com/702446/26942302-662bf17a-4c36-11e7-92aa-c763e15fcf4f.png)
