### ISSUE TITLE
New Feature Type: Telecom Pedestal

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#742]

**Comment by jhudsonWA** [comment]
Id: 151

**Comment by ReedHunter-Wsdot** [comment]
I have it queued up for Jason to add to the Qa geodatabase.  I'll add to the map service after he makes a database table for me.

Btw, I will be out of town Mon -> Wed next week.  If he's available to add the table before 1pm, I'll add this to the map service today.  Otherwise I'll have this in the map service on Thursday of next week.

**Comment by ReedHunter-Wsdot** [comment]
done
