### ISSUE TITLE
AVL: Raw Data Report

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#780]
Ability to report, export to Excel only.
Filtering: Region, Area, MaintenanceVehicle, Start-End Date
Searching one at a time.

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Add to your list, priority is before 10/1, hopefully sooner.

**Comment by joeschmit** [comment]
@jhudsonWA SitRep please?

**Comment by jhudsonWA** [comment]
Yep, was disabled for 5.5 since there was some issues with large amounts of data crashing the site so we will need to narrow it down and make it more #hatsy then we can ship. I’ll tackle it next week and see if I can’t get it out by weeks end. It was close.

- Josh

On Sep 28, 2017, at 3:04 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


SitRep please?

**Comment by joeschmit** [comment]
Thanks bud.

- Schmit

On Sep 28, 2017, at 3:10 PM, Joshua Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:

Yep, was disabled for 5.5 since there was some issues with large amounts of data crashing the site so we will need to narrow it down and make it more #hatsy then we can ship. I’ll tackle it next week and see if I can’t get it out by weeks end. It was close.

- Josh

On Sep 28, 2017, at 3:04 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


SitRep please?

**Comment by jhudsonWA** [comment]
Deployed to prod! Single vehicle, 7 days or less of data at a time. : )
