### ISSUE TITLE
iOS/Web: Add "Due Date" to Planned Feature Activities

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#833]
iOS/Web: Add "Due Date" to Planned Feature Activities, due date will be based on the "End Date" in the planned feature activity Admin screen.

Example: Planned Pending Map> Identify > + Activity > Planned Activities > Due Date...

**Comment by jhudsonWA** [comment]
Done for next version. Shows the max active end date that a particular activity falls under. 

![img_0055](https://user-images.githubusercontent.com/702446/31138422-46e3801e-a823-11e7-8b6f-40f68e57f1c5.png)

**Comment by joeschmit** [comment]
#winning

**Comment by jhudsonWA** [comment]
Bit more information. Planned activities are in a date range. So 1339 - Inspection can fall under multiple.

07/01/17 to 06/30/18
and lets just say as an example it is also defined as
09/01/17 to 08/31/18

In the above example since the current date falls in both those ranges the due date would show 08/31/18.

It's a 5 second fix if you would rather show the min end date 06/30/18.

If a inspection record was done on 10/01/17 then both those ranges would be satisfied. So that's why I did the later of the two if there are overlaps.

**Comment by jhudsonWA** [comment]
Don't expect this to come up too often but as developers we think of edge cases : )

**Comment by joeschmit** [comment]
Hmm, I will consult the team.
