### ISSUE TITLE
Search and Zoom to Lat/Long

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#887]
Requested by Ray (in the case of noxious weed points) as another search by tool on the iPad. Not sure how many would make use of something like this, but he says there are cases when people have a list of features to find and/or to map by lat/long rather than by SRMP. What do you guys think?

**Comment by jhudsonWA** [comment]
Doable

Sent from my iPhone

On Nov 30, 2017, at 7:24 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Requested by Ray (in the case of noxious weed points) as another search by tool on the iPad. Not sure how many would make use of something like this, but he says there are cases when people have a list of features to find and/or to map by lat/long rather than by SRMP. What do you guys think?
