### ISSUE TITLE
New UI Issues: Activities Form Builder

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#933]
![image](https://user-images.githubusercontent.com/16247034/34589696-f0bf5310-f166-11e7-9294-7501897f4e80.png)

Cannot publish form after creating a second Pre-defined follow-up question to a Pre-defined question with a second Pre-defined follow-up question and third follow-up question of any type. For a example: 
1) Region: Pre-defined
    1. Maintenance Area: Pre-defined
        1. ICP: Free Text
Then upon creation of a follow-up to follow-up of Q1 Region...
    2. Maintenance Area: Pre-defined
      <----- _can save/publish form in b/w this and then create next question (ICP) no problem_
       1. ICP: Free Text  <--- After adding this question, hit publish and get the cannot save error.
            
This is modeled after a real currently used form that I know of. This question flow might not be created very often, however still an issue if it is a well-used form and you have to save multiple times to finish, possibly creating multiple version tabs.

![image](https://user-images.githubusercontent.com/16247034/34677409-eddda832-f444-11e7-8c37-057874a36d9f.png)

**Comment by jhudsonWA** [comment]
That’s fun. :) No real changes were on that screen so that’s an existing bug. Which I was told there are several.

On Jan 8, 2018, at 9:58 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/16247034/34589696-f0bf5310-f166-11e7-9294-7501897f4e80.png>

Cannot publish form after creating a second Pre-defined follow-up question to a Pre-defined question with a second Pre-defined follow-up question and third follow-up question of any type. For a example:

  1.  Region: Pre-defined
     *   Maintenance Area: Pre-defined
        *   ICP: Free Text
Then upon creation of a follow-up to follow-up of Q1 Region...
     *   Maintenance Area: Pre-defined
<----- can save/publish form in b/w this and then create next question (ICP) no problem
        *   ICP: Free Text <--- After adding this question, hit publish and get the cannot save error.

This is modeled after a real currently used form that I know of. This question flow might not be created very often, however still an issue if it is a well-used form and you have to save multiple times to finish, possibly creating multiple version tabs.

[image]<https://user-images.githubusercontent.com/16247034/34677409-eddda832-f444-11e7-8c37-057874a36d9f.png>

**Comment by sheppamwsdot** [comment]
This was resolved in an earlier release.
