### ISSUE TITLE
Edit Attributes Toggle - Land Use - Highway Increasing / Highway Decreasing

### ISSUE THREAD

**Issue by PeterBurkhard** [WSDOT/HATS#955]
Kent Night Shift Requested this change for hard to locate Catch Basins and other features.
Would like the option to note increasing or decreasing direction in attributes. 
Example: it's hard to see if the Catch Basin is on the other side of the centerline concrete Jersey Barrier at night in the rain. Would save time if the attribute of Increasing Decreasing could be noted in Land Use / Highway Increasing / Highway Decreasing, with a flick of a toggle. 🙂

<img width="1024" alt="increasing decreasing attributes" src="https://user-images.githubusercontent.com/15268732/35983799-bbedf996-0ca7-11e8-8d90-90ab7add1a54.png">

**Comment by kechinn** [comment]
Easy to do, but it doesn't solve the overall bigger issue we have with feature inventory. Is this for looking at catch basins and other features on the iPad map or if searching by attribute in HATS web? Either way, I'm not sure that would help all that much in locating the features since the feature attributes are hidden from view until they actually open up feature attributes tab or within a activities record. 

I would recommend that when they happen upon a catch basin or other feature that shows the wrong direction, that they edit via the web the _Location_ Attributes to more accurately reflect the correct direction indicator (i.e. Inc/Dec/Both), which is seen on Identify. This ties in with #881 planned for the HATS 3.5 release, which would give users the ability to edit those Location attributes (i.e. SR/SRMP, Dir) via the iPad.

**Comment by PeterBurkhard** [comment]
Oh shoot yeah your right this would be perfect! #881  Love it.
<img width="1057" alt="881" src="https://user-images.githubusercontent.com/15268732/35988650-e4f628d4-0cb3-11e8-844d-6a9e09bc74f0.png">

**Comment by jhudsonWA** [comment]
Oh ya! #881. I should probably code that :) I'll start on it this week.  Lets close this one and track there.
