### ISSUE TITLE
UI Enhancement: Admin File Library URL Filters

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#962]
Can the File Library URL page for Admins get set up with the ability to sort by Category, Name, Description (same as File Library View/Download page)? I think it's currently sorted by oldest add date from top to bottom rather than by Name or Category, so it's sometimes difficult to find an existing item to update.

![image](https://user-images.githubusercontent.com/16247034/36212397-b523ec96-1158-11e8-9567-8eb8639fd3ae.png)

**Comment by jhudsonWA** [comment]
Yep. Assignd to @lundyc-wsdot

**Comment by jhudsonWA** [comment]
Ping @lundyc-wsdot

**Comment by jhudsonWA** [comment]
@lundyc-wsdot Filter info is lost on each filter, can you make it present between post backs?

**Comment by lundyc-wsdot** [comment]
The filtering information is maintained internally through repeated sorting until a different filter is selected.  I blank out the fields so that different filtering, or no filtering, can be easily selected without having to first delete the prior.

This is a feature for convenience.  I can change it, but I don’t think the users would like the alternative.  Your choice …

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
This design go against against pretty much every other page in the app. We leave the values so the user can see what filters they have applied. A simple reset button fixes your concern.

Sent from my iPhone

On Sep 12, 2018, at 6:51 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

The filtering information is maintained internally through repeated sorting until a different filter is selected. I blank out the fields so that different filtering, or no filtering, can be easily selected without having to first delete the prior.

This is a feature for convenience. I can change it, but I don’t think the users would like the alternative. Your choice …

--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by lundyc-wsdot** [comment]
Will do.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by kechinn** [comment]
Awesome, thank you-this looks like it's pretty much done. There are two filters for Region and Maintenance Area though, do they act differently?

**Comment by lundyc-wsdot** [comment]
The region can be filtered to include all maintenance areas in that region.  If a maintenance area is also chosen, only that area in that region will be included.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by jhudsonWA** [comment]
I think she means that there are two on screen. So The Region/Maint Area on left is for adding, the ones on right are for filtering

On Sep 25, 2018, at 8:01 AM, Keisha Chinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome, thank you-this looks like it's pretty much done. There are two filters for Region and Maintenance Area though, do they act differently?

**Comment by jhudsonWA** [comment]
Also it would be good to add similar filters to this screen: http://hatsprod.wsdot.loc/Maintenance/management/activities/FileLibrary



On Sep 25, 2018, at 8:14 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:

The region can be filtered to include all maintenance areas in that region. If a maintenance area is also chosen, only that area in that region will be included.


--
Clay
360-705-7636
WSDOT M/S 47430

"The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge." -- Daniel J. Boorstin

**Comment by kechinn** [comment]
Hahaha, yes, that is what I meant. I realized that one was for adding and the other for filtering almost right after I sent my message. Duh, Keisha. 

I agree with adding similar filters to the regular File Library page.
